import flet as ft

def main(page: ft.Page):
    page.title = "Calcolatrice"
    result = ft.Container(
        bgcolor=ft.colors.WHITE24,
        content=ft.Text(value="0") # Risultato
    )
    page.window_resizable = False
    page.window_width = 400
    page.window_height = 450
    page.vertical_alignment = ft.MainAxisAlignment.CENTER
    page.horizontal_alignment = ft.CrossAxisAlignment.CENTER

    page.add(
        ft.Container(
            width=400,
            height=350,
            padding=10,
            bgcolor=ft.colors.BLACK,
            border_radius=20,
            content=ft.Column(
                controls=[
                ft.Row(controls=[result]), # Row che mostra il risultato
                ft.Row(
                    controls=[
                        ft.ElevatedButton(
                            text="AC",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="+/-",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="%",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,    
                        ),
                        ft.ElevatedButton(
                            text="/",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,    
                        ),
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.ElevatedButton(
                            text="7",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="8",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="9",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="*",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,      
                        ),
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.ElevatedButton(
                            text="4",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="5",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="6",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="-",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,  
                        ),
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.ElevatedButton(
                            text="1",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                        ft.ElevatedButton(
                            text="2",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,    
                        ),
                        ft.ElevatedButton(
                            text="3",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,    
                        ),
                        ft.ElevatedButton(
                            text="+",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                    ]
                ),
                ft.Row(
                    controls=[
                        ft.ElevatedButton(
                            text="0",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,    
                            ),
                        ft.ElevatedButton(
                            text=".",
                            bgcolor=ft.colors.SECONDARY,
                            color=ft.colors.WHITE,
                            expand=1,    
                        ),
                        ft.ElevatedButton(
                            text="=",
                            bgcolor=ft.colors.ORANGE,
                            color=ft.colors.WHITE,
                            expand=1,
                        ),
                    ]
                )
                ]
            )
        )
    )
ft.app(target=main)